### ISSUE TITLE
Consensus fails after upgrading to 0.1.0

### ISSUE THREAD

**Issue by TomL94** [enigmampc/EnigmaBlockchain#71]
On testnet:
Got a full node running 0.0.1. Upgraded the binaries to 0.1.0 (no hard fork).
Got a consensus fail on `enigmad start` :
```bash
I[2020-03-05|12:21:32.301] starting ABCI with Tendermint                module=main 
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected DF41CB6FC605E468CE4F6F1EC7FB5F43B1F9275603341B1252D6CA44DF41D2A0, got 1A792A9EF23596BF27CC6CAA73496C14D1039144D7B7ABE8C2C8705F4A400A0E
```

**Version:** enigmad v0.1.0

**Update:**

Tried fixing with @ethanfrey 's https://github.com/tendermint/iavl/pull/163 , but still getting same results:
```
I[2020-03-05|15:02:08.301] starting ABCI with Tendermint                module=main 
panic: block.AppHash does not match AppHash after replay. Got 65A80EE04090E43CA75C2222CD67A99D01475BC01B6CA136301B2A27FAE0BD6A, expected 9247ACDA295BDAFADC020BDC0FF2ABF4A0AB7DE79BA30C633EFD5DF9B7CA6189.

Block: Block{
  Header{
    Version:        {10 0}
    ChainID:        enigma-testnet
    Height:         147803
    Time:           2020-03-05 11:11:35.380317762 +0000 UTC
    LastBlockID:    82FAE670A64BCF9DB6347A7EB19EEDC62FD79024DF12037C349B9B2E1343D008:1:A807F37EA50A
    LastCommit:     B1EF988AB3312A036AD704ED8D34463BB584B2A44D03CD06E3AD53E373000879
    Data:           
    Validators:     A6CEC5C441B18EF0C6D7D11C57B792F58E8DE4AF4777203046DD7B0CB59C4FD5
    NextValidators: A6CEC5C441B18EF0C6D7D11C57B792F58E8DE4AF4777203046DD7B0CB59C4FD5
    App:            9247ACDA295BDAFADC020BDC0FF2ABF4A0AB7DE79BA30C633EFD5DF9B7CA6189
    Consensus:      048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F
    Results:        
    Evidence:       
    Proposer:       CB5D5EC3F2E377998CB80DDC702803A74FC69C86
  }#3A143C79C75A03813D112F5C54CA639887960FDFDD2EFC4069FD3D9023E78633
  Data{
    
  }#
  EvidenceData{
    
  }#
  Commit{
    Height:     147802
    Round:      0
    BlockID:    82FAE670A64BCF9DB6347A7EB19EEDC62FD79024DF12037C349B9B2E1343D008:1:A807F37EA50A
    Signatures:
      CommitSig{E8DB29532603 by CB5D5EC3F2E3 on 2 @ 2020-03-05T11:11:35.380317762Z}
  }#
}#3A143C79C75A03813D112F5C54CA639887960FDFDD2EFC4069FD3D9023E78633
```

**Comment by assafmo** [comment]
Why it is not a hard fork?

**Comment by TomL94** [comment]
Tried fixing with @ethanfrey 's https://github.com/tendermint/iavl/pull/163 , but still getting same results:
```
I[2020-03-05|15:02:08.301] starting ABCI with Tendermint                module=main 
panic: block.AppHash does not match AppHash after replay. Got 65A80EE04090E43CA75C2222CD67A99D01475BC01B6CA136301B2A27FAE0BD6A, expected 9247ACDA295BDAFADC020BDC0FF2ABF4A0AB7DE79BA30C633EFD5DF9B7CA6189.

Block: Block{
  Header{
    Version:        {10 0}
    ChainID:        enigma-testnet
    Height:         147803
    Time:           2020-03-05 11:11:35.380317762 +0000 UTC
    LastBlockID:    82FAE670A64BCF9DB6347A7EB19EEDC62FD79024DF12037C349B9B2E1343D008:1:A807F37EA50A
    LastCommit:     B1EF988AB3312A036AD704ED8D34463BB584B2A44D03CD06E3AD53E373000879
    Data:           
    Validators:     A6CEC5C441B18EF0C6D7D11C57B792F58E8DE4AF4777203046DD7B0CB59C4FD5
    NextValidators: A6CEC5C441B18EF0C6D7D11C57B792F58E8DE4AF4777203046DD7B0CB59C4FD5
    App:            9247ACDA295BDAFADC020BDC0FF2ABF4A0AB7DE79BA30C633EFD5DF9B7CA6189
    Consensus:      048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F
    Results:        
    Evidence:       
    Proposer:       CB5D5EC3F2E377998CB80DDC702803A74FC69C86
  }#3A143C79C75A03813D112F5C54CA639887960FDFDD2EFC4069FD3D9023E78633
  Data{
    
  }#
  EvidenceData{
    
  }#
  Commit{
    Height:     147802
    Round:      0
    BlockID:    82FAE670A64BCF9DB6347A7EB19EEDC62FD79024DF12037C349B9B2E1343D008:1:A807F37EA50A
    Signatures:
      CommitSig{E8DB29532603 by CB5D5EC3F2E3 on 2 @ 2020-03-05T11:11:35.380317762Z}
  }#
}#3A143C79C75A03813D112F5C54CA639887960FDFDD2EFC4069FD3D9023E78633
```

**Comment by ethanfrey** [comment]
All nodes must run the same binary. You may have patches 0.38.0 to 0.38.1 that *should* not change the state, but any major change will produce a different app hash. This happens if the two nodes produced even one bit of different in the stored data.

If you are producing it with the exact same binaries and same data, then it is a bug in the code (some non-deterministic behavior).

In the above case, it seems lik user error. To update the binary, you must coordinate that **every node on the blockchain** updates the binary at the **exact same height**. This is quite tricky and the approach of the Cosmos Hub is to dump-state-and-restart (eg. export the data, and start a new blockchain with new binaries after applying some json migration). I do not like this, and worked with Regen Network to develop an inline upgrade, which will force halt the chain, and let the users swap out binaries, possibly apply a code-defined migration and continue. I even built out https://github.com/regen-network/cosmosd to automate that. However, I have not done this in practice for quite some time.

If you wish to use the "standard" upgrade approach, check out Cosmos Discord and talk to the core devs.

If you want to try the newer inline upgrade, please join Regen's Telegram channel and join their upcoming testnet (in one week?) where they will run through this procedure. You can learn how it works in a controlled environment, then try it out on your testnet.

**Comment by TomL94** [comment]
Thanks @ethanfrey ! I did not synchronize the block height of upgrade, and therefore got the error as you said. I'm glad we learn these things on testnet :)
I wonder though, If I do a hard fork and somewhere down the road a new full node wants to join, they have to start syncing from block 1. They will run the new binaries from the beginning, so won't this be a problem for syncing earlier blocks (prior to hard fork)?

**Comment by ethanfrey** [comment]
That's exactly what Regen's upgrade module (mainline as of cosmos-sdk v0.38.0) and `cosmosd` aim  to do. Make this easy, and potentially auto-download binaries for non-validating full-nodes.

Do join their group - it's the cutting edge of the cosmos ecosystem and we have seen upgrades completed withing 2 minutes, with many node operators AFK. (Compared to 2-4 hours for cosmos hub). They are running another testcase (with `wasmd v0.7.0`) next week.

**Comment by TomL94** [comment]
As mentioned, exported the state at the specific height of the upgrade and used it to reset the node.
Used https://github.com/cosmos/cosmos-sdk/wiki/Cosmos-Hub-1-Upgrade for reference.
Thanks again, @ethanfrey !
